### ISSUE TITLE
Prompt is not shown correctly

### ISSUE THREAD

**Issue by CallumHoward** [psprint/history-search-multi-word#4]
Hi, thanks for a great plugin.
I have tried it out and unfortunately it seems to mess up my prompt. This can be seen here:
[![asciicast](https://asciinema.org/a/8a2b5x86tgjj9on083vsgipk7.png)](https://asciinema.org/a/8a2b5x86tgjj9on083vsgipk7)

```bash
$PROMPT = %{%}#%{%} %{%}%n %{%}at %{%}MacBook-Pro %{%}in %{%}${PWD/#$HOME/~}%{%}$(ys_hg_prompt_info)$(git_prompt_info)
%{%}$ %{%}
$RPS1 = $(vi_mode_prompt_info)
```

I am using [this vi-mode plugin](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/vi-mode), and setting it to put NORMAL in the right prompt, as can be seen in the video.
Any ideas on why this is occurring, and how I could fix it?

**Comment by psprint** [comment]
Try latest version, HEAD 2f6393d, tag v1.1.1. Does it help?

**Comment by CallumHoward** [comment]
This is an improvement, the prompt is displayed correctly, however the right prompt $RPS1 does something strange:
[![asciicast](https://asciinema.org/a/4nrctoprp47ncsjhy05agd5ae.png)](https://asciinema.org/a/4nrctoprp47ncsjhy05agd5ae)

**Comment by psprint** [comment]
The plugin defines own keymap "hsmw". Apparently the vi-mode plugin displays keymap name, like "normal". Thinking what can be done about this.

**Comment by psprint** [comment]
I've added explicit support for the vi-mode plugin, happy using!

**Comment by CallumHoward** [comment]
Wow, this is perfect -- thank you!
