### ISSUE TITLE
Ctrl-N/P not working in context mode

### ISSUE THREAD

**Issue by CallumHoward** [psprint/history-search-multi-word#6]
Thanks for the new feature!

Ctrl-N/P work for me in the default mode, but when I press Ctrl-K, Ctrl-N/P don't cause any change. I can still move up and down with the arrow keys however. If I switch back to the default mode with Ctrl-K, Ctrl-N/P works again.

Let me know if there are any details I can provide to help.

**Comment by psprint** [comment]
Maybe there is only one occurrence of the command? Number of occurrences is shown at end of the header.

**Comment by CallumHoward** [comment]
Oh yes, that is right. I misunderstood how it works.

**Comment by psprint** [comment]
I'm glad it's working, it would be hard to track what's wrong because the ^N/^P binding code is rather plain :)
